### PR TITLE
Add 'persistence' option, so visiting a file need not kill sr.

### PR DESCRIPTION
**Pull request by Boruch-Baum**
+ create defcustom boolean variable 'sr-persist'.
+ alter function 'sr-find-regular-file' accordingly.

### CODE REVIEW

**Comment by escherdragon** [comment]
Hi Boruch,

Thank you for your contribution. As it stands, though, there are two problems I see with it:

1. It doesn't really make sense in a text-only console (does it?)
2. The same functionality can be easily achieved using the [popviewer extension](https://www.emacswiki.org/emacs/Sunrise_Commander#toc5) and possibly remapping Enter to do `sr-quick-view` instead of `sr-advertised-find-file` in your own local configuration.

Let me know what you think.

Cheers,
--
José A. Romero L.
escherdragon@gmail.com

**Comment by Boruch-Baum** [comment]
Hi. Thanks for sharing/contributing what looks like may be a replacement for my use of midnight commander!

You asked:"It doesn't really make sense in a text-only console (does it?)"

For me, and for others who use midnight commander and emacs in a text only console, it certainly does. When I switch to midnight commander (either using tmux or %), I can expect to get the familiar double pane. When it doesn't appear, because I had prior used an mc internal plugin or feature, returning to the file presentation returns me to the same double pane. It's the attract of the double pane features that keep bringing me back to it. But with sunrise commander, it's too easy to lose that double-pane presentation. Then I need to either hunt for the panes(buffers) and put them in a frame's windows, or use ibuffer to find them and do the same.

You comment: "The same functionality can be easily achieved using the popviewer extension".

That is the entire point! Quick view should be DIFFERENT from finding a file, otherwise why even offer the difference. Midnight commander has it right, in that quick view opens a read-only panel that easily reverts to the double panel midnight commander. In fact, I wrote the patch BECAUSE of frustration with the sunrise commander version of quick view.

**Comment by Boruch-Baum** [comment]
BTW, on the subject of quickview: Is there a known issue / problem with the keybinding 'C-u v' to close a quick view buffer? It doesn't working for me. My environment is debian/i3wm/tmux console/emacs 25.2 nox.

**Comment by escherdragon** [comment]
Hi Boruch,

At last I found a little time to address this issue. I have implemented the feature in a slightly different way, in order to make it more flexible, extensible and hopefully better suited to your needs.

I have added a new custom variable `sr-visit-buffer-function`, with three assignable values:

1. `sr-visit-buffer-in-current-frame` which quits SC and displays the newly opened buffer in the same frame, just like it has always done, this is the default value,
2. `special-display-popup-frame` (defined in `window.el`) which creates a brand new _dedicated_ frame to display the buffer. This frame is automatically destroyed when the buffer is killed.
3. The `Other` option allows to provide an arbitrary function to display the buffer. It may be whatever you like, the buffer to display is passed as the only argument to this function.

Let me know your thoughts, whether this solution satisfies your requirements, or if you'd still like to see any other changes in the code.

Cheers,
--
José A. Romero L.
escherdragon@gmail.com

**Comment by escherdragon** [comment]
You also asked whether there are any known issues with the "C-u v" shortcut for closing quick view buffers. No, I have just checked that on three different computers (LInux, OS X and Windows), it's working fine everywhere. Maybe your console emulator is intercepting the C-u prefix and not letting it get through to Emacs?

Cheers,
--
José A. Romero L.
escherdragon@gmail.com

**Comment by Boruch-Baum** [comment]
> I have added a new custom variable sr-visit-buffer-function, with three assignable values:
> ...
> Let me know your thoughts

I'll see if I have time to look at the update later today. Based only upon your description, my initial question would be whether 'sr' distinguishes functionally between (in mc terms) opening a file, and quick-viewing a file. Technically, we are now straying from the strict anrrow scope of the start of this thread, so if you want me to open the following as an issue, that's fine. The distinction that a user of mc would expect (and which makes sense to me) is that opening a file creates a new buffer in a new emacs pane with full read-write emacs features, while quick viewing a file re-uses the same read-only buffer, and appears in one window of the sunrise commander frame. Thus, for example, a user in quick view mode can scroll through a list of files and not have to worry that he is creating a zillion buffers that will need to be manually killed later.

> whether this solution satisfies your requirements, or if you'd still like to see any other changes in the code.

Thanks for the consideration. I wasn't looking for what I thought was personally unusual, just trying to help adjust the code's behavior to be more like midnight commander. Of course, there's no requirement for sunrise commander to behave exactly like midnight commander, but on this point, I thought there was sense and usefulness in how midnight commander behaves.

**Comment by Boruch-Baum** [comment]
> You also asked whether there are any known issues with the "C-u v" shortcut for closing quick view buffers. No, I have just checked that on three different computers (LInux, OS X and Windows), it's working fine everywhere. Maybe your console emulator is intercepting the C-u prefix and not letting it get through to Emacs?

No, must be something else. Emacs includes a key-logger called "M-x view-lossage" (C-h l [that's lower-case L]). From within an sr window, when I type "o C-u o C-u v", the key-logger window result correctly shows: 
```
 o [sr-popviewer-quick-view]
 C-u [universal-argument]
 o [sr-popviewer-quick-view]
 C-u [universal-argument]
 v [sr-popviewer-quick-view]
 C-h l [view-lossage]
```

**Comment by lassik** [comment]
Closing this PR for now since it proposes a substantial new feature last worked on in 2017. There's been a lot of refactoring to the SC codebase so adding will be difficult. We should concentrate on fixing bugs in the existing features and defer complex new work until we have a solid MELPA package.

**Comment by lassik** [comment]
To be sure, we can revisit this once we have the MELPA package.

**Pull request closed without merging**
