### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by zonuexe**
This Makefile generates a byte compilation of Lisp files and an "autoloads" file.  It is useful for autoloading commands without relying on the package manager.

### CODE REVIEW

**Comment by lassik** [comment]
Thank you for contributing!

I don't know anything about Cask so I trust that your file is correct :) What does the `"6"` mean in `(package "sunrise-commander" "6" ...)`? Is it ok to have `(source melpa)` and `(source gnu)` in there even though we're not in either of those package repositories yet?

The Makefile seems to be using some GNU make extensions as I can't build it with `bsdmake`, so we should probably rename it to `GNUmakefile`.

**Comment by zonuexe** [comment]
> I don't know anything about Cask so I trust that your file is correct :) What does the "6" mean in `(package "sunrise-commander" "6" ...)`? Is it ok to have `(source melpa)` and `(source gnu)` in there even though we're not in either of those package repositories yet?

This version number refers to `sunrise-commander.el`. This number is not associated with any package repository.

> The Makefile seems to be using some GNU make extensions as I can't build it with `bsdmake`, so we should probably rename it to `GNUmakefile`. Of course, if you know of an easy way to convert it to portable `make` syntax, so much the better.

I'm sorry. I will fix it.

**Comment by zonuexe** [comment]
@lassik I fixed it.

**Comment by lassik** [comment]
> I'm sorry. I will fix it.

No problem :) Thanks for making the changes. The new Makefile works perfectly with `bsdmake`. Merging.

**Pull request merged**
