### PR TITLE
Rename Lisp package to "sunrise"

### PR DESCRIPTION
**Pull request by lassik**
This PR contains:

* Two huge commits to systematically rename almost everything.
* Many small commits after those to fix up some little things.

It's much easier to review the PR commit-by-commit than to look at the full diff. I tried to break down the commits logically and write descriptive commit messages.

@escherdragon @zonuexe I'll wait for an OK from both of you before merging. Thanks!

### CODE REVIEW

**Comment by lassik** [comment]
The long discussion that led to this PR is in issue #75

**Comment by zonuexe** [comment]
@lassik Great works! I will check out this PR tonight and see how it works.

**Comment by zonuexe** [comment]
@lassik Sorry for the late review. The change looks good.

I had to make a few changes to Makefile to build these files:

```patch
diff --git a/Makefile b/Makefile
index 3878d81..e8da596 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 EMACS ?= emacs
-ELS = sunrise.el sunrise-buttons.el sunrise-checkpoints.el sunrise-loop.el sunrise-mirror.el sunrise-modeline.el sunrise-old-checkpoints.el sunrise-popviewer.el sunrise-tabs.el sunrise-tree.el sunrise-w32-addons.el
+ELS = sunrise.el sunrise-buttons.el sunrise-checkpoint.el sunrise-loop.el sunrise-mirror.el sunrise-modeline.el sunrise-checkpoint-old.el sunrise-popviewer.el sunrise-tabs.el sunrise-tree.el sunrise-w32.el
 
 AUTOLOADS = sunrise-autoloads.el
 ELCS = $(ELS:.el=.elc)
```

**Comment by lassik** [comment]
No problem. I forgot to commit the Makefile changes, thanks for pointing that out.

Since José hasn't responded yet and said it's ok for us to merge PRs, let's just merge this in. The changes are so big that we'll probably find some more problems; we can fix them as we find them.

**Pull request merged**
